---
abstract: "Dancer2's plugin for Locale::Wolowitz"
author:
  - 'Menno Blom <blom@cpan.org>'
build_requires:
  Test::More: '0.96'
  Test::TCP: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.141170'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dancer2-Plugin-Locale-Wolowitz
no_index:
  directory:
    - t
    - inc
requires:
  Dancer2: '0'
  Locale::Wolowitz: '0'
  perl: '5.001'
resources:
  repository: https://github.com/b10m/p5-Dancer2-Plugin-Locale-Wolowitz
version: '0.02'
